### ISSUE TITLE
сделать привязку кнопок в ресете или типа того

### ISSUE THREAD

**Issue by xfynx** [Two9A/jsGB#2]
есть идея сделать эти кнопки на картинке как раз для задавания кнопок управления, а не для самого управления, соответственно надо будет как-то сопоставлять коды кнопок с названием

**Comment by twe4ked** [comment]
Google translate:

> there is an idea to make these buttons on the picture just for setting the control buttons, and not for the control itself, respectively, it will be necessary to somehow compare the codes of the buttons with the name
